# Codecov configuration file
# See https://docs.codecov.com/docs/codecovyml-reference for more information
coverage:
  status:
    project:
      default:
        target: 0%
    patch:
      default:
        target: 0%
        informational: true
